version: '3.8'

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: aleksanderdulepov/django_todolist_repo:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - ./.env
    ports:
        - 8000:8000
    depends_on:
      postgres:
        condition:
          service_healthy
      migrations:
        condition:
          service_completed_successfully
  migrations:
    image: aleksanderdulepov/django_todolist_repo:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: python manage.py migrate
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition:
          service_healthy
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -d ${DB_NAME} -U ${DB_USER}
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  postgres_data: