version: '3.8'

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: aleksanderdulepov/django_todolist_repo:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code/
    ports:
        - 8000:8000
    depends_on:
        - migrations
        - postgres
  migrations:
    image: aleksanderdulepov/django_todolist_repo:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: python manage.py migrate
    volumes:
      - .:/code/
    depends_on:
      - postgres
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 3s
      timeout: 3s
      retries: 3


volumes:
  postgres_data: