version: '3.8'

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
        - 8000:8000
    depends_on:
        - migrations
        - postgres
  migrations:
    build: .
    command: python manage.py migrate --no-input
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB},
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD},
      POSTGRES_USER: ${POSTGRES_USER},
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 3s
      timeout: 3s
      retries: 3


volumes:
  postgres_data: