# Generated by Django 4.0.1 on 2023-01-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_alter_tguser_options_tguser_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='fk_user_id',
        ),
        migrations.AddField(
            model_name='tguser',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=models.IntegerField(choices=[(0, 'Первый визит'), (1, 'Еще не авторизованный'), (2, 'Авторизованный'), (3, 'Выбор категории'), (4, 'Ввод названия цели')], default=0, verbose_name='Состояние'),
        ),
    ]
